### ISSUE TITLE
Shorter URL?

### ISSUE THREAD

**Issue by GitBoudewijn** [aalfiann/imgproxify#1]
Hello,

I just found out about your service and it looks really nice. The only thing I think would be nicer is if the url could be shorter.

So instead of `cdn.imgproxify.com/image?url=` you could have `cdn.imgproxify.com/?url=` or if that's not possible `cdn.imgproxify.com/i?url=`.

It would also be nice if you could omit the 'http://' part of the url so you could just do something like `cdn.imgproxify.com/?url=example.com/x.jpg`.

**Comment by aalfiann** [comment]
1. The reason I put scheme on url is to eliminates check the ssl protocol on the image url. So this will not fixed.

2. This url `cdn.imgproxify.com/?url=` is not possible because has been used to render template engine.  but the url `cdn.imgproxify.com/i?url=` is possible.

Thank you for your idea, I'll work on this for the next release.

**Comment by aalfiann** [comment]
Sorry, I have to close this issue because: 

1. I decided to not using short url because it will require a database server to save the long path.
2. `cdn.imgproxify.com/i?url=` still would be a long url if the url image content is long.

So this issue is won't fix..
I'm really sorry.
